    save_best: True
    plot_agents: False
    collect_stats: False

    log_dir: ./tmp
    video_dir: ${log_dir}/videos

    hydra:
      run:
        dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ${log_dir}
      cache_size: 10000
      every_n_seconds: 10
      verbose: False

    algorithm:

      seed:
        train: 0
        eval: 8
        q: 1
        act: 2
        explorer: 4
        torch: 7

      n_envs: 1
      n_steps_train: 10
      n_steps: 5e6
      buffer_size: 1e6
      tau_target: 0.005
      optim_n_updates: 4
      eval_interval: 2500
      learning_starts: 10000
      nb_evals: 1
      max_grad_norm: 0.5
      batch_size: 256
      action_noise: 0.03
      discount_factor: 1.0
      architecture:
        actor_hidden_size: [64, 64]
        critic_hidden_size: [512, 512]

    gym_env:
      env_name: SwimmerBBRLEnv-v0
      xml_file: swimmer3.xml

    actor_optimizer:
      classname: torch.optim.Adam
      lr: 0.006
      eps: 5e-5
    
    critic_optimizer:
      classname: torch.optim.Adam
      lr: 0.006
      eps: 5e-5
