    save_best: True
    plot_agents: False

    log_dir: ./tmp
    video_dir: ${log_dir}/videos

    hydra:
      run:
        dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ${log_dir}
      cache_size: 10000
      every_n_seconds: 10
      verbose: False

    algorithm:

      seed:
        train: 0
        eval: 8
        q: 1
        act: 2
        explorer: 4
        torch: 7

      n_envs: 1
      n_steps_train: 80
      n_steps: 5e6
      buffer_size: 1e6
      tau_target: 0.005
      optim_n_updates: 3
      eval_interval: 2500
      learning_starts: 10000
      nb_evals: 1
      max_grad_norm: 0.5
      batch_size: 256
      action_noise: 0.2
      discount_factor: 1.0
      architecture:
        actor_hidden_size: [32, 32]
        critic_hidden_size: [256, 256]

    gym_env:
      env_name: Swimmer-v3

    actor_optimizer:
      classname: torch.optim.Adam
      lr: 0.0002
    
    critic_optimizer:
      classname: torch.optim.Adam
      lr: 0.001
