save_best: True
plot_agents: False
collect_stats: False

log_dir: ./tmp
video_dir: ${log_dir}/videos

hydra:
      run:
            dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ${log_dir}
      cache_size: 10000
      every_n_seconds: 10
      verbose: False

algorithm:

      seed:
            train: 334
            eval: 983
            q: 123
            explorer: 456
            torch: 7

      n_envs: 1
      n_steps_train: 10
      n_steps: 5e6
      eval_interval: 2500
      nb_evals: 2
      buffer_size: 1e6
      batch_size: 256
      learning_starts: 10_000
      tau_target: 0.005
      max_grad_norm: 0.5
      discount_factor: 0.9999

      entropy_mode: "auto" # "auto" or "fixed"
      init_entropy_coef: 0.2
      actor_type: SquashedGaussianActorNew
      architecture:
            actor_hidden_size: [64, 64] 
            critic_hidden_size: [512, 512] 


      # Note: Swimmer-v3 is deprecated, but Swimmer-v4 does not seem to accept an xml_file
gym_env:
      env_name: SwimmerBBRLEnv-v0
      xml_file: swimmer3.xml

actor_optimizer:
      classname: torch.optim.Adam
      lr: 0.0003
      eps: 5e-5

critic_optimizer:
      classname: torch.optim.Adam
      lr: 0.0003
      eps: 5e-5

entropy_coef_optimizer:
      classname: torch.optim.Adam
      lr: 0.0003
      eps: 1e-5
